### ISSUE TITLE
Container 

### ISSUE THREAD

**Issue by MironenkoDeveloper** [Andrii-Yukhymenko/exe#5]
https://github.com/Andrii-Yukhymenko/exe/blob/5990988884bcd80af7b911eb593a5c7c3c385148/scss/style.scss#L244

> .contaier , не правильно обращаться к классу компонента, нужно добавлять  модификатор типа .services__container

**Comment by Andrii-Yukhymenko** [comment]
<div class="container services__container"></div>
Так?

**Comment by Andrii-Yukhymenko** [comment]
<div class="container services__container"></div>

**Comment by Andrii-Yukhymenko** [comment]
`<div` class="container services__container"></div> 
Так?
